/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "08250d47cff7dea1d6679569c5e6d4252908484a"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
