/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "9dbda74896ff44c5799255c33ca655f25f5ba320"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
